import type { MovementPoint } from '../types/scene';
import {
  MAP_CENTER,
  generateMovementPoints,
  hashSeed,
  mulberry32,
  offsetCoordinate,
  pointInPolygon,
} from '../services/geometryUtils';
import { mockCameras } from './mockCameras';
import { getEntityById, mockEntities } from './mockEntities';
import { getPathById } from './mockPaths';
import { mockZones } from './mockZones';
import { SIM_DURATION_SEC, SIM_START_MS } from './simWindow';

/**
 * Assignment of every moving entity to its path geometry. Movement points
 * are generated by walking each entity along its assigned LineString at the
 * given speed — entities never leave their lane / path / waterway.
 */
export interface MovementAssignment {
  entityId: string;
  pathId: string;
  speedKmh: number;
  startDistanceM: number;
}

export const movementAssignments: MovementAssignment[] = [
  // Vehicles on road lanes
  { entityId: 'VEH-001', pathId: 'LANE-N2-E', speedKmh: 32, startDistanceM: 60 },
  { entityId: 'VEH-002', pathId: 'LANE-N2-W', speedKmh: 28, startDistanceM: 300 },
  { entityId: 'VEH-003', pathId: 'LANE-N1-E', speedKmh: 38, startDistanceM: 150 },
  { entityId: 'VEH-004', pathId: 'LANE-N3-W', speedKmh: 30, startDistanceM: 480 },
  { entityId: 'VEH-005', pathId: 'LANE-V2-N', speedKmh: 24, startDistanceM: 200 },
  { entityId: 'VEH-006', pathId: 'LANE-V3-S', speedKmh: 35, startDistanceM: 90 },

  // Shuttle on its loop route
  { entityId: 'SHUTTLE-001', pathId: 'SHUTTLE-LOOP-01', speedKmh: 17, startDistanceM: 0 },

  // People on pedestrian paths
  { entityId: 'PERSON-001', pathId: 'PED-01', speedKmh: 4.2, startDistanceM: 0 },
  { entityId: 'PERSON-002', pathId: 'PED-01', speedKmh: 3.8, startDistanceM: 120 },
  { entityId: 'PERSON-003', pathId: 'PED-02', speedKmh: 4.6, startDistanceM: 40 },
  { entityId: 'PERSON-004', pathId: 'PED-02', speedKmh: 4.0, startDistanceM: 180 },
  { entityId: 'PERSON-005', pathId: 'PED-03', speedKmh: 5.0, startDistanceM: 60 },
  { entityId: 'PERSON-006', pathId: 'PED-03', speedKmh: 4.4, startDistanceM: 350 },
  { entityId: 'PERSON-007', pathId: 'PARK-01', speedKmh: 4.8, startDistanceM: 100 },
  { entityId: 'PERSON-008', pathId: 'PED-01', speedKmh: 5.4, startDistanceM: 260 },

  // Pets on park paths
  { entityId: 'PET-001', pathId: 'PARK-01', speedKmh: 6.5, startDistanceM: 30 },
  { entityId: 'PET-002', pathId: 'PARK-02', speedKmh: 5.0, startDistanceM: 10 },

  // Boats on the waterway
  { entityId: 'BOAT-001', pathId: 'WATERWAY-01', speedKmh: 9, startDistanceM: 100 },
  { entityId: 'BOAT-002', pathId: 'WATERWAY-01', speedKmh: 7, startDistanceM: 450 },

  // Floating waste drifting with the water flow
  { entityId: 'WASTE-001', pathId: 'WATERFLOW-01', speedKmh: 1.6, startDistanceM: 80 },
  { entityId: 'WASTE-002', pathId: 'WATERFLOW-01', speedKmh: 1.2, startDistanceM: 220 },
  { entityId: 'WASTE-003', pathId: 'WATERFLOW-01', speedKmh: 1.9, startDistanceM: 400 },
  { entityId: 'WASTE-004', pathId: 'WATERFLOW-01', speedKmh: 1.0, startDistanceM: 560 },
];

/** Stationary incident objects: fixed position + reporting camera. */
const incidentPositions: Record<string, { east: number; north: number; cameraId?: string }> = {
  'INCIDENT-001': { east: -50, north: 16, cameraId: 'CAM-ROAD-01' },
  'INCIDENT-002': { east: 243, north: -100, cameraId: 'CAM-ZONE-01' },
  'INCIDENT-003': { east: -330, north: 60, cameraId: 'CAM-WATER-01' },
};

function generateIncidentPoints(entityId: string): MovementPoint[] {
  const spec = incidentPositions[entityId];
  const [lng, lat] = offsetCoordinate(MAP_CENTER, spec.east, spec.north);
  const zone = mockZones.find((z) => pointInPolygon([lng, lat], z.geometry));
  const rng = mulberry32(hashSeed(entityId));
  const points: MovementPoint[] = [];
  for (let t = 0; t <= SIM_DURATION_SEC; t += 15) {
    points.push({
      entity_id: entityId,
      observed_at: new Date(SIM_START_MS + t * 1000).toISOString(),
      lng,
      lat,
      heading_deg: 0,
      speed_kmh: 0,
      zone_id: zone?.zone_id,
      source_camera_id: spec.cameraId,
      confidence: Math.round((0.86 + rng() * 0.1) * 100) / 100,
      tracking_status: 'tracked',
    });
  }
  return points;
}

function buildAllMovementPoints(): Record<string, MovementPoint[]> {
  const byEntity: Record<string, MovementPoint[]> = {};

  for (const assignment of movementAssignments) {
    const entity = getEntityById(assignment.entityId);
    const path = getPathById(assignment.pathId);
    if (!entity || !path) continue;
    byEntity[assignment.entityId] = generateMovementPoints(
      entity,
      path,
      SIM_START_MS,
      SIM_DURATION_SEC,
      assignment.speedKmh,
      {
        startDistanceM: assignment.startDistanceM,
        cameras: mockCameras,
        zones: mockZones,
      },
    );
  }

  for (const incident of mockEntities.filter((e) => e.entity_type === 'incident_object')) {
    byEntity[incident.entity_id] = generateIncidentPoints(incident.entity_id);
  }

  return byEntity;
}

/**
 * Full mock movement database: 30 minutes of points, 1 point per second per
 * moving entity, generated in memory at app startup from path geometry.
 */
export const movementPointsByEntity: Record<string, MovementPoint[]> = buildAllMovementPoints();
